package order

import com.example.droolsdemo.po.Order


/*所购图书总价在100元以下的没有优惠*/
rule "order-1"
    when
        $order:Order(originalPrice<100)
    then
        $order.setRealPrice($order.getOriginalPrice());
        System.out.println("订单规则1");
end

/*所购图书总价在100到200元的优惠20元*/
rule "order-2"
    when
        $order:Order(originalPrice>=100 && originalPrice<200)
    then
        $order.setRealPrice($order.getOriginalPrice()-20);
        System.out.println("订单规则2");
end
/*所购图书总价在200到300元的优惠50元*/
rule "order-3"
    when
        $order:Order(originalPrice>=200&&originalPrice<300)
    then
        $order.setRealPrice($order.getOriginalPrice()-50);
        System.out.println("订单规则3");
end

/*所购图书总价在300元以上的优惠100元*/
rule "order-4"
    when
        $order:Order($o:originalPrice>=300)
    then
    System.err.println($o);
    $order.setRealPrice($order.getOriginalPrice()-100);
    System.out.println("订单规则4");
end
